/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxLiveRouteImport } from './routes/inbox-live'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWaConnectionRouteImport } from './routes/_app/wa-connection'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOfficersRouteImport } from './routes/_app/officers'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContentRouteImport } from './routes/_app/content'
import { Route as AppChatbotRouteImport } from './routes/_app/chatbot'
import { Route as AppBlastRouteImport } from './routes/_app/blast'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxLiveRoute = InboxLiveRouteImport.update({
  id: '/inbox-live',
  path: '/inbox-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaConnectionRoute = AppWaConnectionRouteImport.update({
  id: '/wa-connection',
  path: '/wa-connection',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOfficersRoute = AppOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppBlastRoute = AppBlastRouteImport.update({
  id: '/blast',
  path: '/blast',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox-live': typeof InboxLiveRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/blast': typeof AppBlastRoute
  '/chatbot': typeof AppChatbotRoute
  '/content': typeof AppContentRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/officers': typeof AppOfficersRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/wa-connection': typeof AppWaConnectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox-live': typeof InboxLiveRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/blast': typeof AppBlastRoute
  '/chatbot': typeof AppChatbotRoute
  '/content': typeof AppContentRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/officers': typeof AppOfficersRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/wa-connection': typeof AppWaConnectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/inbox-live': typeof InboxLiveRoute
  '/login': typeof LoginRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/blast': typeof AppBlastRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/content': typeof AppContentRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/officers': typeof AppOfficersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/wa-connection': typeof AppWaConnectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox-live'
    | '/login'
    | '/api-keys'
    | '/blast'
    | '/chatbot'
    | '/content'
    | '/dashboard'
    | '/inbox'
    | '/officers'
    | '/settings'
    | '/templates'
    | '/users'
    | '/wa-connection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox-live'
    | '/login'
    | '/api-keys'
    | '/blast'
    | '/chatbot'
    | '/content'
    | '/dashboard'
    | '/inbox'
    | '/officers'
    | '/settings'
    | '/templates'
    | '/users'
    | '/wa-connection'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/inbox-live'
    | '/login'
    | '/_app/api-keys'
    | '/_app/blast'
    | '/_app/chatbot'
    | '/_app/content'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/officers'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/users'
    | '/_app/wa-connection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InboxLiveRoute: typeof InboxLiveRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-live': {
      id: '/inbox-live'
      path: '/inbox-live'
      fullPath: '/inbox-live'
      preLoaderRoute: typeof InboxLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wa-connection': {
      id: '/_app/wa-connection'
      path: '/wa-connection'
      fullPath: '/wa-connection'
      preLoaderRoute: typeof AppWaConnectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/officers': {
      id: '/_app/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof AppOfficersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blast': {
      id: '/_app/blast'
      path: '/blast'
      fullPath: '/blast'
      preLoaderRoute: typeof AppBlastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBlastRoute: typeof AppBlastRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppContentRoute: typeof AppContentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppOfficersRoute: typeof AppOfficersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWaConnectionRoute: typeof AppWaConnectionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBlastRoute: AppBlastRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppContentRoute: AppContentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppOfficersRoute: AppOfficersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWaConnectionRoute: AppWaConnectionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InboxLiveRoute: InboxLiveRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
